name: Update webhook messages

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Uwierzytelnienie
      id: generate-token
      uses: actions/create-github-app-token@v2
      with:
        app-id: ${{ vars.APP_ID }}
        private-key: ${{ secrets.APP_PRIVATE_KEY }}
    - name: Pobranie repozytorium
      uses: actions/checkout@v4
    - name: Instalacja Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: 'npm'
    - name: Instalacja bibliotek
      run: npm ci
    - name: Wczytanie tajnych danych
      uses: oNaiPs/secrets-to-env-action@v1
      with:
        secrets: ${{ toJSON(secrets) }}
    - name: Uruchomienie skryptu
      run: node src/update.js
    - name: Aktualizacja repozytorium o linki do stworzonych wiadomości
      env:
        GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
      run: |
        git config user.email "github-actions@github.com"
        git config user.name "github-actions"
        git add .
        git commit -m "Dodanie linków do stworzonych wiadomości" || echo "Nic nowego"
        git push

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
