name: Update webhook messages

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: 'npm'
    - run: npm ci
    - uses: oNaiPs/secrets-to-env-action@v1
      with:
        secrets: ${{ toJSON(secrets) }}
    - run: node src/update.js
    - run: |
        git config user.email "github-actions@github.com"
        git config user.name "github-actions"
        git add .
        git commit -m "Dodanie linków do stworzonych wiadomości" && git push || echo "Nic nowego"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
