name: Update webhook messages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: 'npm'
    - run: npm ci
    - uses: oNaiPs/secrets-to-env-action@v1
      with:
        secrets: ${{ toJSON(secrets) }}
    - run: node src/process.js
    - run: node src/update.js

concurrency:
  group: ${{ github.workflow }}-$BRANCH_NAME
  cancel-in-progress: true
